<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::statement(
            "INSERT INTO `cities` (`id`, `province_id`, `city_name`, `city_name_full`, `city_type`, `city_lat`, `city_lon`) VALUES
            (1101, 11, 'simeulue', 'kabupaten simeulue', 'kabupaten', NULL, NULL),
            (1102, 11, 'aceh singkil', 'kabupaten aceh singkil', 'kabupaten', NULL, NULL),
            (1103, 11, 'aceh selatan', 'kabupaten aceh selatan', 'kabupaten', NULL, NULL),
            (1104, 11, 'aceh tenggara', 'kabupaten aceh tenggara', 'kabupaten', NULL, NULL),
            (1105, 11, 'aceh timur', 'kabupaten aceh timur', 'kabupaten', NULL, NULL),
            (1106, 11, 'aceh tengah', 'kabupaten aceh tengah', 'kabupaten', NULL, NULL),
            (1107, 11, 'aceh barat', 'kabupaten aceh barat', 'kabupaten', NULL, NULL),
            (1108, 11, 'aceh besar', 'kabupaten aceh besar', 'kabupaten', NULL, NULL),
            (1109, 11, 'pidie', 'kabupaten pidie', 'kabupaten', NULL, NULL),
            (1110, 11, 'bireuen', 'kabupaten bireuen', 'kabupaten', NULL, NULL),
            (1111, 11, 'aceh utara', 'kabupaten aceh utara', 'kabupaten', NULL, NULL),
            (1112, 11, 'aceh barat daya', 'kabupaten aceh barat daya', 'kabupaten', NULL, NULL),
            (1113, 11, 'gayo lues', 'kabupaten gayo lues', 'kabupaten', NULL, NULL),
            (1114, 11, 'aceh tamiang', 'kabupaten aceh tamiang', 'kabupaten', NULL, NULL),
            (1115, 11, 'nagan raya', 'kabupaten nagan raya', 'kabupaten', NULL, NULL),
            (1116, 11, 'aceh jaya', 'kabupaten aceh jaya', 'kabupaten', NULL, NULL),
            (1117, 11, 'bener meriah', 'kabupaten bener meriah', 'kabupaten', NULL, NULL),
            (1118, 11, 'pidie jaya', 'kabupaten pidie jaya', 'kabupaten', NULL, NULL),
            (1171, 11, 'banda aceh', 'kota banda aceh', 'kota', NULL, NULL),
            (1172, 11, 'sabang', 'kota sabang', 'kota', NULL, NULL),
            (1173, 11, 'langsa', 'kota langsa', 'kota', NULL, NULL),
            (1174, 11, 'lhokseumawe', 'kota lhokseumawe', 'kota', NULL, NULL),
            (1175, 11, 'subulussalam', 'kota subulussalam', 'kota', NULL, NULL),
            (1201, 12, 'nias', 'kabupaten nias', 'kabupaten', NULL, NULL),
            (1202, 12, 'mandailing natal', 'kabupaten mandailing natal', 'kabupaten', NULL, NULL),
            (1203, 12, 'tapanuli selatan', 'kabupaten tapanuli selatan', 'kabupaten', NULL, NULL),
            (1204, 12, 'tapanuli tengah', 'kabupaten tapanuli tengah', 'kabupaten', NULL, NULL),
            (1205, 12, 'tapanuli utara', 'kabupaten tapanuli utara', 'kabupaten', NULL, NULL),
            (1206, 12, 'toba samosir', 'kabupaten toba samosir', 'kabupaten', NULL, NULL),
            (1207, 12, 'labuhan batu', 'kabupaten labuhan batu', 'kabupaten', NULL, NULL),
            (1208, 12, 'asahan', 'kabupaten asahan', 'kabupaten', NULL, NULL),
            (1209, 12, 'simalungun', 'kabupaten simalungun', 'kabupaten', NULL, NULL),
            (1210, 12, 'dairi', 'kabupaten dairi', 'kabupaten', NULL, NULL),
            (1211, 12, 'karo', 'kabupaten karo', 'kabupaten', NULL, NULL),
            (1212, 12, 'deli serdang', 'kabupaten deli serdang', 'kabupaten', NULL, NULL),
            (1213, 12, 'langkat', 'kabupaten langkat', 'kabupaten', NULL, NULL),
            (1214, 12, 'nias selatan', 'kabupaten nias selatan', 'kabupaten', NULL, NULL),
            (1215, 12, 'humbang hasundutan', 'kabupaten humbang hasundutan', 'kabupaten', NULL, NULL),
            (1216, 12, 'pakpak bharat', 'kabupaten pakpak bharat', 'kabupaten', NULL, NULL),
            (1217, 12, 'samosir', 'kabupaten samosir', 'kabupaten', NULL, NULL),
            (1218, 12, 'serdang bedagai', 'kabupaten serdang bedagai', 'kabupaten', NULL, NULL),
            (1219, 12, 'batu bara', 'kabupaten batu bara', 'kabupaten', NULL, NULL),
            (1220, 12, 'padang lawas utara', 'kabupaten padang lawas utara', 'kabupaten', NULL, NULL),
            (1221, 12, 'padang lawas', 'kabupaten padang lawas', 'kabupaten', NULL, NULL),
            (1222, 12, 'labuhan batu selatan', 'kabupaten labuhan batu selatan', 'kabupaten', NULL, NULL),
            (1223, 12, 'labuhan batu utara', 'kabupaten labuhan batu utara', 'kabupaten', NULL, NULL),
            (1224, 12, 'nias utara', 'kabupaten nias utara', 'kabupaten', NULL, NULL),
            (1225, 12, 'nias barat', 'kabupaten nias barat', 'kabupaten', NULL, NULL),
            (1271, 12, 'sibolga', 'kota sibolga', 'kota', NULL, NULL),
            (1272, 12, 'tanjung balai', 'kota tanjung balai', 'kota', NULL, NULL),
            (1273, 12, 'pematang siantar', 'kota pematang siantar', 'kota', NULL, NULL),
            (1274, 12, 'tebing tinggi', 'kota tebing tinggi', 'kota', NULL, NULL),
            (1275, 12, 'medan', 'kota medan', 'kota', NULL, NULL),
            (1276, 12, 'binjai', 'kota binjai', 'kota', NULL, NULL),
            (1277, 12, 'padangsidimpuan', 'kota padangsidimpuan', 'kota', NULL, NULL),
            (1278, 12, 'gunungsitoli', 'kota gunungsitoli', 'kota', NULL, NULL),
            (1301, 13, 'kepulauan mentawai', 'kabupaten kepulauan mentawai', 'kabupaten', NULL, NULL),
            (1302, 13, 'pesisir selatan', 'kabupaten pesisir selatan', 'kabupaten', NULL, NULL),
            (1303, 13, 'solok', 'kabupaten solok', 'kabupaten', NULL, NULL),
            (1304, 13, 'sijunjung', 'kabupaten sijunjung', 'kabupaten', NULL, NULL),
            (1305, 13, 'tanah datar', 'kabupaten tanah datar', 'kabupaten', NULL, NULL),
            (1306, 13, 'padang pariaman', 'kabupaten padang pariaman', 'kabupaten', NULL, NULL),
            (1307, 13, 'agam', 'kabupaten agam', 'kabupaten', NULL, NULL),
            (1308, 13, 'lima puluh kota', 'kabupaten lima puluh kota', 'kabupaten', NULL, NULL),
            (1309, 13, 'pasaman', 'kabupaten pasaman', 'kabupaten', NULL, NULL),
            (1310, 13, 'solok selatan', 'kabupaten solok selatan', 'kabupaten', NULL, NULL),
            (1311, 13, 'dharmasraya', 'kabupaten dharmasraya', 'kabupaten', NULL, NULL),
            (1312, 13, 'pasaman barat', 'kabupaten pasaman barat', 'kabupaten', NULL, NULL),
            (1371, 13, 'padang', 'kota padang', 'kota', NULL, NULL),
            (1372, 13, 'solok', 'kota solok', 'kota', NULL, NULL),
            (1373, 13, 'sawah lunto', 'kota sawah lunto', 'kota', NULL, NULL),
            (1374, 13, 'padang panjang', 'kota padang panjang', 'kota', NULL, NULL),
            (1375, 13, 'bukittinggi', 'kota bukittinggi', 'kota', NULL, NULL),
            (1376, 13, 'payakumbuh', 'kota payakumbuh', 'kota', NULL, NULL),
            (1377, 13, 'pariaman', 'kota pariaman', 'kota', NULL, NULL),
            (1401, 14, 'kuantan singingi', 'kabupaten kuantan singingi', 'kabupaten', NULL, NULL),
            (1402, 14, 'indragiri hulu', 'kabupaten indragiri hulu', 'kabupaten', NULL, NULL),
            (1403, 14, 'indragiri hilir', 'kabupaten indragiri hilir', 'kabupaten', NULL, NULL),
            (1404, 14, 'pelalawan', 'kabupaten pelalawan', 'kabupaten', NULL, NULL),
            (1405, 14, 'siak', 'kabupaten siak', 'kabupaten', NULL, NULL),
            (1406, 14, 'kampar', 'kabupaten kampar', 'kabupaten', NULL, NULL),
            (1407, 14, 'rokan hulu', 'kabupaten rokan hulu', 'kabupaten', NULL, NULL),
            (1408, 14, 'bengkalis', 'kabupaten bengkalis', 'kabupaten', NULL, NULL),
            (1409, 14, 'rokan hilir', 'kabupaten rokan hilir', 'kabupaten', NULL, NULL),
            (1410, 14, 'kepulauan meranti', 'kabupaten kepulauan meranti', 'kabupaten', NULL, NULL),
            (1471, 14, 'pekanbaru', 'kota pekanbaru', 'kota', NULL, NULL),
            (1473, 14, 'dumai', 'kota dumai', 'kota', NULL, NULL),
            (1501, 15, 'kerinci', 'kabupaten kerinci', 'kabupaten', NULL, NULL),
            (1502, 15, 'merangin', 'kabupaten merangin', 'kabupaten', NULL, NULL),
            (1503, 15, 'sarolangun', 'kabupaten sarolangun', 'kabupaten', NULL, NULL),
            (1504, 15, 'batang hari', 'kabupaten batang hari', 'kabupaten', NULL, NULL),
            (1505, 15, 'muaro jambi', 'kabupaten muaro jambi', 'kabupaten', NULL, NULL),
            (1506, 15, 'tanjung jabung timur', 'kabupaten tanjung jabung timur', 'kabupaten', NULL, NULL),
            (1507, 15, 'tanjung jabung barat', 'kabupaten tanjung jabung barat', 'kabupaten', NULL, NULL),
            (1508, 15, 'tebo', 'kabupaten tebo', 'kabupaten', NULL, NULL),
            (1509, 15, 'bungo', 'kabupaten bungo', 'kabupaten', NULL, NULL),
            (1571, 15, 'jambi', 'kota jambi', 'kota', NULL, NULL),
            (1572, 15, 'sungai penuh', 'kota sungai penuh', 'kota', NULL, NULL),
            (1601, 16, 'ogan komering ulu', 'kabupaten ogan komering ulu', 'kabupaten', NULL, NULL),
            (1602, 16, 'ogan komering ilir', 'kabupaten ogan komering ilir', 'kabupaten', NULL, NULL),
            (1603, 16, 'muara enim', 'kabupaten muara enim', 'kabupaten', NULL, NULL),
            (1604, 16, 'lahat', 'kabupaten lahat', 'kabupaten', NULL, NULL),
            (1605, 16, 'musi rawas', 'kabupaten musi rawas', 'kabupaten', NULL, NULL),
            (1606, 16, 'musi banyuasin', 'kabupaten musi banyuasin', 'kabupaten', NULL, NULL),
            (1607, 16, 'banyu asin', 'kabupaten banyu asin', 'kabupaten', NULL, NULL),
            (1608, 16, 'ogan komering ulu selatan', 'kabupaten ogan komering ulu selatan', 'kabupaten', NULL, NULL),
            (1609, 16, 'ogan komering ulu timur', 'kabupaten ogan komering ulu timur', 'kabupaten', NULL, NULL),
            (1610, 16, 'ogan ilir', 'kabupaten ogan ilir', 'kabupaten', NULL, NULL),
            (1611, 16, 'empat lawang', 'kabupaten empat lawang', 'kabupaten', NULL, NULL),
            (1671, 16, 'palembang', 'kota palembang', 'kota', NULL, NULL),
            (1672, 16, 'prabumulih', 'kota prabumulih', 'kota', NULL, NULL),
            (1673, 16, 'pagar alam', 'kota pagar alam', 'kota', NULL, NULL),
            (1674, 16, 'lubuklinggau', 'kota lubuklinggau', 'kota', NULL, NULL),
            (1701, 17, 'bengkulu selatan', 'kabupaten bengkulu selatan', 'kabupaten', NULL, NULL),
            (1702, 17, 'rejang lebong', 'kabupaten rejang lebong', 'kabupaten', NULL, NULL),
            (1703, 17, 'bengkulu utara', 'kabupaten bengkulu utara', 'kabupaten', NULL, NULL),
            (1704, 17, 'kaur', 'kabupaten kaur', 'kabupaten', NULL, NULL),
            (1705, 17, 'seluma', 'kabupaten seluma', 'kabupaten', NULL, NULL),
            (1706, 17, 'mukomuko', 'kabupaten mukomuko', 'kabupaten', NULL, NULL),
            (1707, 17, 'lebong', 'kabupaten lebong', 'kabupaten', NULL, NULL),
            (1708, 17, 'kepahiang', 'kabupaten kepahiang', 'kabupaten', NULL, NULL),
            (1709, 17, 'bengkulu tengah', 'kabupaten bengkulu tengah', 'kabupaten', NULL, NULL),
            (1771, 17, 'bengkulu', 'kota bengkulu', 'kota', NULL, NULL),
            (1801, 18, 'lampung barat', 'kabupaten lampung barat', 'kabupaten', NULL, NULL),
            (1802, 18, 'tanggamus', 'kabupaten tanggamus', 'kabupaten', NULL, NULL),
            (1803, 18, 'lampung selatan', 'kabupaten lampung selatan', 'kabupaten', NULL, NULL),
            (1804, 18, 'lampung timur', 'kabupaten lampung timur', 'kabupaten', NULL, NULL),
            (1805, 18, 'lampung tengah', 'kabupaten lampung tengah', 'kabupaten', NULL, NULL),
            (1806, 18, 'lampung utara', 'kabupaten lampung utara', 'kabupaten', NULL, NULL),
            (1807, 18, 'way kanan', 'kabupaten way kanan', 'kabupaten', NULL, NULL),
            (1808, 18, 'tulangbawang', 'kabupaten tulangbawang', 'kabupaten', NULL, NULL),
            (1809, 18, 'pesawaran', 'kabupaten pesawaran', 'kabupaten', NULL, NULL),
            (1810, 18, 'pringsewu', 'kabupaten pringsewu', 'kabupaten', NULL, NULL),
            (1811, 18, 'mesuji', 'kabupaten mesuji', 'kabupaten', NULL, NULL),
            (1812, 18, 'tulang bawang barat', 'kabupaten tulang bawang barat', 'kabupaten', NULL, NULL),
            (1813, 18, 'pesisir barat', 'kabupaten pesisir barat', 'kabupaten', NULL, NULL),
            (1871, 18, 'bandar lampung', 'kota bandar lampung', 'kota', NULL, NULL),
            (1872, 18, 'metro', 'kota metro', 'kota', NULL, NULL),
            (1901, 19, 'bangka', 'kabupaten bangka', 'kabupaten', NULL, NULL),
            (1902, 19, 'belitung', 'kabupaten belitung', 'kabupaten', NULL, NULL),
            (1903, 19, 'bangka barat', 'kabupaten bangka barat', 'kabupaten', NULL, NULL),
            (1904, 19, 'bangka tengah', 'kabupaten bangka tengah', 'kabupaten', NULL, NULL),
            (1905, 19, 'bangka selatan', 'kabupaten bangka selatan', 'kabupaten', NULL, NULL),
            (1906, 19, 'belitung timur', 'kabupaten belitung timur', 'kabupaten', NULL, NULL),
            (1971, 19, 'pangkal pinang', 'kota pangkal pinang', 'kota', NULL, NULL),
            (2101, 21, 'karimun', 'kabupaten karimun', 'kabupaten', NULL, NULL),
            (2102, 21, 'bintan', 'kabupaten bintan', 'kabupaten', NULL, NULL),
            (2103, 21, 'natuna', 'kabupaten natuna', 'kabupaten', NULL, NULL),
            (2104, 21, 'lingga', 'kabupaten lingga', 'kabupaten', NULL, NULL),
            (2105, 21, 'kepulauan anambas', 'kabupaten kepulauan anambas', 'kabupaten', NULL, NULL),
            (2171, 21, 'batam', 'kota batam', 'kota', NULL, NULL),
            (2172, 21, 'tanjung pinang', 'kota tanjung pinang', 'kota', NULL, NULL),
            (3101, 31, 'kepulauan seribu', 'kabupaten kepulauan seribu', 'kabupaten', NULL, NULL),
            (3171, 31, 'jakarta selatan', 'kota jakarta selatan', 'kota', NULL, NULL),
            (3172, 31, 'jakarta timur', 'kota jakarta timur', 'kota', NULL, NULL),
            (3173, 31, 'jakarta pusat', 'kota jakarta pusat', 'kota', NULL, NULL),
            (3174, 31, 'jakarta barat', 'kota jakarta barat', 'kota', NULL, NULL),
            (3175, 31, 'jakarta utara', 'kota jakarta utara', 'kota', NULL, NULL),
            (3201, 32, 'bogor', 'kabupaten bogor', 'kabupaten', NULL, NULL),
            (3202, 32, 'sukabumi', 'kabupaten sukabumi', 'kabupaten', NULL, NULL),
            (3203, 32, 'cianjur', 'kabupaten cianjur', 'kabupaten', NULL, NULL),
            (3204, 32, 'bandung', 'kabupaten bandung', 'kabupaten', NULL, NULL),
            (3205, 32, 'garut', 'kabupaten garut', 'kabupaten', NULL, NULL),
            (3206, 32, 'tasikmalaya', 'kabupaten tasikmalaya', 'kabupaten', NULL, NULL),
            (3207, 32, 'ciamis', 'kabupaten ciamis', 'kabupaten', NULL, NULL),
            (3208, 32, 'kuningan', 'kabupaten kuningan', 'kabupaten', NULL, NULL),
            (3209, 32, 'cirebon', 'kabupaten cirebon', 'kabupaten', NULL, NULL),
            (3210, 32, 'majalengka', 'kabupaten majalengka', 'kabupaten', NULL, NULL),
            (3211, 32, 'sumedang', 'kabupaten sumedang', 'kabupaten', NULL, NULL),
            (3212, 32, 'indramayu', 'kabupaten indramayu', 'kabupaten', NULL, NULL),
            (3213, 32, 'subang', 'kabupaten subang', 'kabupaten', NULL, NULL),
            (3214, 32, 'purwakarta', 'kabupaten purwakarta', 'kabupaten', NULL, NULL),
            (3215, 32, 'karawang', 'kabupaten karawang', 'kabupaten', NULL, NULL),
            (3216, 32, 'bekasi', 'kabupaten bekasi', 'kabupaten', NULL, NULL),
            (3217, 32, 'bandung barat', 'kabupaten bandung barat', 'kabupaten', NULL, NULL),
            (3218, 32, 'pangandaran', 'kabupaten pangandaran', 'kabupaten', NULL, NULL),
            (3271, 32, 'bogor', 'kota bogor', 'kota', NULL, NULL),
            (3272, 32, 'sukabumi', 'kota sukabumi', 'kota', NULL, NULL),
            (3273, 32, 'bandung', 'kota bandung', 'kota', NULL, NULL),
            (3274, 32, 'cirebon', 'kota cirebon', 'kota', NULL, NULL),
            (3275, 32, 'bekasi', 'kota bekasi', 'kota', NULL, NULL),
            (3276, 32, 'depok', 'kota depok', 'kota', NULL, NULL),
            (3277, 32, 'cimahi', 'kota cimahi', 'kota', NULL, NULL),
            (3278, 32, 'tasikmalaya', 'kota tasikmalaya', 'kota', NULL, NULL),
            (3279, 32, 'banjar', 'kota banjar', 'kota', NULL, NULL),
            (3301, 33, 'cilacap', 'kabupaten cilacap', 'kabupaten', NULL, NULL),
            (3302, 33, 'banyumas', 'kabupaten banyumas', 'kabupaten', NULL, NULL),
            (3303, 33, 'purbalingga', 'kabupaten purbalingga', 'kabupaten', NULL, NULL),
            (3304, 33, 'banjarnegara', 'kabupaten banjarnegara', 'kabupaten', NULL, NULL),
            (3305, 33, 'kebumen', 'kabupaten kebumen', 'kabupaten', NULL, NULL),
            (3306, 33, 'purworejo', 'kabupaten purworejo', 'kabupaten', NULL, NULL),
            (3307, 33, 'wonosobo', 'kabupaten wonosobo', 'kabupaten', NULL, NULL),
            (3308, 33, 'magelang', 'kabupaten magelang', 'kabupaten', NULL, NULL),
            (3309, 33, 'boyolali', 'kabupaten boyolali', 'kabupaten', NULL, NULL),
            (3310, 33, 'klaten', 'kabupaten klaten', 'kabupaten', NULL, NULL),
            (3311, 33, 'sukoharjo', 'kabupaten sukoharjo', 'kabupaten', NULL, NULL),
            (3312, 33, 'wonogiri', 'kabupaten wonogiri', 'kabupaten', NULL, NULL),
            (3313, 33, 'karanganyar', 'kabupaten karanganyar', 'kabupaten', NULL, NULL),
            (3314, 33, 'sragen', 'kabupaten sragen', 'kabupaten', NULL, NULL),
            (3315, 33, 'grobogan', 'kabupaten grobogan', 'kabupaten', NULL, NULL),
            (3316, 33, 'blora', 'kabupaten blora', 'kabupaten', NULL, NULL),
            (3317, 33, 'rembang', 'kabupaten rembang', 'kabupaten', NULL, NULL),
            (3318, 33, 'pati', 'kabupaten pati', 'kabupaten', NULL, NULL),
            (3319, 33, 'kudus', 'kabupaten kudus', 'kabupaten', NULL, NULL),
            (3320, 33, 'jepara', 'kabupaten jepara', 'kabupaten', NULL, NULL),
            (3321, 33, 'demak', 'kabupaten demak', 'kabupaten', NULL, NULL),
            (3322, 33, 'semarang', 'kabupaten semarang', 'kabupaten', NULL, NULL),
            (3323, 33, 'temanggung', 'kabupaten temanggung', 'kabupaten', NULL, NULL),
            (3324, 33, 'kendal', 'kabupaten kendal', 'kabupaten', NULL, NULL),
            (3325, 33, 'batang', 'kabupaten batang', 'kabupaten', NULL, NULL),
            (3326, 33, 'pekalongan', 'kabupaten pekalongan', 'kabupaten', NULL, NULL),
            (3327, 33, 'pemalang', 'kabupaten pemalang', 'kabupaten', NULL, NULL),
            (3328, 33, 'tegal', 'kabupaten tegal', 'kabupaten', NULL, NULL),
            (3329, 33, 'brebes', 'kabupaten brebes', 'kabupaten', NULL, NULL),
            (3371, 33, 'magelang', 'kota magelang', 'kota', NULL, NULL),
            (3372, 33, 'surakarta', 'kota surakarta', 'kota', NULL, NULL),
            (3373, 33, 'salatiga', 'kota salatiga', 'kota', NULL, NULL),
            (3374, 33, 'semarang', 'kota semarang', 'kota', NULL, NULL),
            (3375, 33, 'pekalongan', 'kota pekalongan', 'kota', NULL, NULL),
            (3376, 33, 'tegal', 'kota tegal', 'kota', NULL, NULL),
            (3401, 34, 'kulon progo', 'kabupaten kulon progo', 'kabupaten', NULL, NULL),
            (3402, 34, 'bantul', 'kabupaten bantul', 'kabupaten', NULL, NULL),
            (3403, 34, 'gunung kidul', 'kabupaten gunung kidul', 'kabupaten', NULL, NULL),
            (3404, 34, 'sleman', 'kabupaten sleman', 'kabupaten', NULL, NULL),
            (3471, 34, 'yogyakarta', 'kota yogyakarta', 'kota', NULL, NULL),
            (3501, 35, 'pacitan', 'kabupaten pacitan', 'kabupaten', NULL, NULL),
            (3502, 35, 'ponorogo', 'kabupaten ponorogo', 'kabupaten', NULL, NULL),
            (3503, 35, 'trenggalek', 'kabupaten trenggalek', 'kabupaten', NULL, NULL),
            (3504, 35, 'tulungagung', 'kabupaten tulungagung', 'kabupaten', NULL, NULL),
            (3505, 35, 'blitar', 'kabupaten blitar', 'kabupaten', NULL, NULL),
            (3506, 35, 'kediri', 'kabupaten kediri', 'kabupaten', NULL, NULL),
            (3507, 35, 'malang', 'kabupaten malang', 'kabupaten', NULL, NULL),
            (3508, 35, 'lumajang', 'kabupaten lumajang', 'kabupaten', NULL, NULL),
            (3509, 35, 'jember', 'kabupaten jember', 'kabupaten', NULL, NULL),
            (3510, 35, 'banyuwangi', 'kabupaten banyuwangi', 'kabupaten', NULL, NULL),
            (3511, 35, 'bondowoso', 'kabupaten bondowoso', 'kabupaten', NULL, NULL),
            (3512, 35, 'situbondo', 'kabupaten situbondo', 'kabupaten', NULL, NULL),
            (3513, 35, 'probolinggo', 'kabupaten probolinggo', 'kabupaten', NULL, NULL),
            (3514, 35, 'pasuruan', 'kabupaten pasuruan', 'kabupaten', NULL, NULL),
            (3515, 35, 'sidoarjo', 'kabupaten sidoarjo', 'kabupaten', NULL, NULL),
            (3516, 35, 'mojokerto', 'kabupaten mojokerto', 'kabupaten', NULL, NULL),
            (3517, 35, 'jombang', 'kabupaten jombang', 'kabupaten', NULL, NULL),
            (3518, 35, 'nganjuk', 'kabupaten nganjuk', 'kabupaten', NULL, NULL),
            (3519, 35, 'madiun', 'kabupaten madiun', 'kabupaten', NULL, NULL),
            (3520, 35, 'magetan', 'kabupaten magetan', 'kabupaten', NULL, NULL),
            (3521, 35, 'ngawi', 'kabupaten ngawi', 'kabupaten', NULL, NULL),
            (3522, 35, 'bojonegoro', 'kabupaten bojonegoro', 'kabupaten', NULL, NULL),
            (3523, 35, 'tuban', 'kabupaten tuban', 'kabupaten', NULL, NULL),
            (3524, 35, 'lamongan', 'kabupaten lamongan', 'kabupaten', NULL, NULL),
            (3525, 35, 'gresik', 'kabupaten gresik', 'kabupaten', NULL, NULL),
            (3526, 35, 'bangkalan', 'kabupaten bangkalan', 'kabupaten', NULL, NULL),
            (3527, 35, 'sampang', 'kabupaten sampang', 'kabupaten', NULL, NULL),
            (3528, 35, 'pamekasan', 'kabupaten pamekasan', 'kabupaten', NULL, NULL),
            (3529, 35, 'sumenep', 'kabupaten sumenep', 'kabupaten', NULL, NULL),
            (3571, 35, 'kediri', 'kota kediri', 'kota', NULL, NULL),
            (3572, 35, 'blitar', 'kota blitar', 'kota', NULL, NULL),
            (3573, 35, 'malang', 'kota malang', 'kota', NULL, NULL),
            (3574, 35, 'probolinggo', 'kota probolinggo', 'kota', NULL, NULL),
            (3575, 35, 'pasuruan', 'kota pasuruan', 'kota', NULL, NULL),
            (3576, 35, 'mojokerto', 'kota mojokerto', 'kota', NULL, NULL),
            (3577, 35, 'madiun', 'kota madiun', 'kota', NULL, NULL),
            (3578, 35, 'surabaya', 'kota surabaya', 'kota', NULL, NULL),
            (3579, 35, 'batu', 'kota batu', 'kota', NULL, NULL),
            (3601, 36, 'pandeglang', 'kabupaten pandeglang', 'kabupaten', NULL, NULL),
            (3602, 36, 'lebak', 'kabupaten lebak', 'kabupaten', NULL, NULL),
            (3603, 36, 'tangerang', 'kabupaten tangerang', 'kabupaten', NULL, NULL),
            (3604, 36, 'serang', 'kabupaten serang', 'kabupaten', NULL, NULL),
            (3671, 36, 'tangerang', 'kota tangerang', 'kota', NULL, NULL),
            (3672, 36, 'cilegon', 'kota cilegon', 'kota', NULL, NULL),
            (3673, 36, 'serang', 'kota serang', 'kota', NULL, NULL),
            (3674, 36, 'tangerang selatan', 'kota tangerang selatan', 'kota', NULL, NULL),
            (5101, 51, 'jembrana', 'kabupaten jembrana', 'kabupaten', NULL, NULL),
            (5102, 51, 'tabanan', 'kabupaten tabanan', 'kabupaten', NULL, NULL),
            (5103, 51, 'badung', 'kabupaten badung', 'kabupaten', NULL, NULL),
            (5104, 51, 'gianyar', 'kabupaten gianyar', 'kabupaten', NULL, NULL),
            (5105, 51, 'klungkung', 'kabupaten klungkung', 'kabupaten', NULL, NULL),
            (5106, 51, 'bangli', 'kabupaten bangli', 'kabupaten', NULL, NULL),
            (5107, 51, 'karang asem', 'kabupaten karang asem', 'kabupaten', NULL, NULL),
            (5108, 51, 'buleleng', 'kabupaten buleleng', 'kabupaten', NULL, NULL),
            (5171, 51, 'denpasar', 'kota denpasar', 'kota', NULL, NULL),
            (5201, 52, 'lombok barat', 'kabupaten lombok barat', 'kabupaten', NULL, NULL),
            (5202, 52, 'lombok tengah', 'kabupaten lombok tengah', 'kabupaten', NULL, NULL),
            (5203, 52, 'lombok timur', 'kabupaten lombok timur', 'kabupaten', NULL, NULL),
            (5204, 52, 'sumbawa', 'kabupaten sumbawa', 'kabupaten', NULL, NULL),
            (5205, 52, 'dompu', 'kabupaten dompu', 'kabupaten', NULL, NULL),
            (5206, 52, 'bima', 'kabupaten bima', 'kabupaten', NULL, NULL),
            (5207, 52, 'sumbawa barat', 'kabupaten sumbawa barat', 'kabupaten', NULL, NULL),
            (5208, 52, 'lombok utara', 'kabupaten lombok utara', 'kabupaten', NULL, NULL),
            (5271, 52, 'mataram', 'kota mataram', 'kota', NULL, NULL),
            (5272, 52, 'bima', 'kota bima', 'kota', NULL, NULL),
            (5301, 53, 'sumba barat', 'kabupaten sumba barat', 'kabupaten', NULL, NULL),
            (5302, 53, 'sumba timur', 'kabupaten sumba timur', 'kabupaten', NULL, NULL),
            (5303, 53, 'kupang', 'kabupaten kupang', 'kabupaten', NULL, NULL),
            (5304, 53, 'timor tengah selatan', 'kabupaten timor tengah selatan', 'kabupaten', NULL, NULL),
            (5305, 53, 'timor tengah utara', 'kabupaten timor tengah utara', 'kabupaten', NULL, NULL),
            (5306, 53, 'belu', 'kabupaten belu', 'kabupaten', NULL, NULL),
            (5307, 53, 'alor', 'kabupaten alor', 'kabupaten', NULL, NULL),
            (5308, 53, 'lembata', 'kabupaten lembata', 'kabupaten', NULL, NULL),
            (5309, 53, 'flores timur', 'kabupaten flores timur', 'kabupaten', NULL, NULL),
            (5310, 53, 'sikka', 'kabupaten sikka', 'kabupaten', NULL, NULL),
            (5311, 53, 'ende', 'kabupaten ende', 'kabupaten', NULL, NULL),
            (5312, 53, 'ngada', 'kabupaten ngada', 'kabupaten', NULL, NULL),
            (5313, 53, 'manggarai', 'kabupaten manggarai', 'kabupaten', NULL, NULL),
            (5314, 53, 'rote ndao', 'kabupaten rote ndao', 'kabupaten', NULL, NULL),
            (5315, 53, 'manggarai barat', 'kabupaten manggarai barat', 'kabupaten', NULL, NULL),
            (5316, 53, 'sumba tengah', 'kabupaten sumba tengah', 'kabupaten', NULL, NULL),
            (5317, 53, 'sumba barat daya', 'kabupaten sumba barat daya', 'kabupaten', NULL, NULL),
            (5318, 53, 'nagekeo', 'kabupaten nagekeo', 'kabupaten', NULL, NULL),
            (5319, 53, 'manggarai timur', 'kabupaten manggarai timur', 'kabupaten', NULL, NULL),
            (5320, 53, 'sabu raijua', 'kabupaten sabu raijua', 'kabupaten', NULL, NULL),
            (5371, 53, 'kupang', 'kota kupang', 'kota', NULL, NULL),
            (6101, 61, 'sambas', 'kabupaten sambas', 'kabupaten', NULL, NULL),
            (6102, 61, 'bengkayang', 'kabupaten bengkayang', 'kabupaten', NULL, NULL),
            (6103, 61, 'landak', 'kabupaten landak', 'kabupaten', NULL, NULL),
            (6104, 61, 'pontianak', 'kabupaten pontianak', 'kabupaten', NULL, NULL),
            (6105, 61, 'sanggau', 'kabupaten sanggau', 'kabupaten', NULL, NULL),
            (6106, 61, 'ketapang', 'kabupaten ketapang', 'kabupaten', NULL, NULL),
            (6107, 61, 'sintang', 'kabupaten sintang', 'kabupaten', NULL, NULL),
            (6108, 61, 'kapuas hulu', 'kabupaten kapuas hulu', 'kabupaten', NULL, NULL),
            (6109, 61, 'sekadau', 'kabupaten sekadau', 'kabupaten', NULL, NULL),
            (6110, 61, 'melawi', 'kabupaten melawi', 'kabupaten', NULL, NULL),
            (6111, 61, 'kayong utara', 'kabupaten kayong utara', 'kabupaten', NULL, NULL),
            (6112, 61, 'kubu raya', 'kabupaten kubu raya', 'kabupaten', NULL, NULL),
            (6171, 61, 'pontianak', 'kota pontianak', 'kota', NULL, NULL),
            (6172, 61, 'singkawang', 'kota singkawang', 'kota', NULL, NULL),
            (6201, 62, 'kotawaringin barat', 'kabupaten kotawaringin barat', 'kabupaten', NULL, NULL),
            (6202, 62, 'kotawaringin timur', 'kabupaten kotawaringin timur', 'kabupaten', NULL, NULL),
            (6203, 62, 'kapuas', 'kabupaten kapuas', 'kabupaten', NULL, NULL),
            (6204, 62, 'barito selatan', 'kabupaten barito selatan', 'kabupaten', NULL, NULL),
            (6205, 62, 'barito utara', 'kabupaten barito utara', 'kabupaten', NULL, NULL),
            (6206, 62, 'sukamara', 'kabupaten sukamara', 'kabupaten', NULL, NULL),
            (6207, 62, 'lamandau', 'kabupaten lamandau', 'kabupaten', NULL, NULL),
            (6208, 62, 'seruyan', 'kabupaten seruyan', 'kabupaten', NULL, NULL),
            (6209, 62, 'katingan', 'kabupaten katingan', 'kabupaten', NULL, NULL),
            (6210, 62, 'pulang pisau', 'kabupaten pulang pisau', 'kabupaten', NULL, NULL),
            (6211, 62, 'gunung mas', 'kabupaten gunung mas', 'kabupaten', NULL, NULL),
            (6212, 62, 'barito timur', 'kabupaten barito timur', 'kabupaten', NULL, NULL),
            (6213, 62, 'murung raya', 'kabupaten murung raya', 'kabupaten', NULL, NULL),
            (6271, 62, 'palangka raya', 'kota palangka raya', 'kota', NULL, NULL),
            (6301, 63, 'tanah laut', 'kabupaten tanah laut', 'kabupaten', NULL, NULL),
            (6302, 63, 'baru', 'kabupaten kota baru', 'kabupaten', NULL, NULL),
            (6303, 63, 'banjar', 'kabupaten banjar', 'kabupaten', NULL, NULL),
            (6304, 63, 'barito kuala', 'kabupaten barito kuala', 'kabupaten', NULL, NULL),
            (6305, 63, 'tapin', 'kabupaten tapin', 'kabupaten', NULL, NULL),
            (6306, 63, 'hulu sungai selatan', 'kabupaten hulu sungai selatan', 'kabupaten', NULL, NULL),
            (6307, 63, 'hulu sungai tengah', 'kabupaten hulu sungai tengah', 'kabupaten', NULL, NULL),
            (6308, 63, 'hulu sungai utara', 'kabupaten hulu sungai utara', 'kabupaten', NULL, NULL),
            (6309, 63, 'tabalong', 'kabupaten tabalong', 'kabupaten', NULL, NULL),
            (6310, 63, 'tanah bumbu', 'kabupaten tanah bumbu', 'kabupaten', NULL, NULL),
            (6311, 63, 'balangan', 'kabupaten balangan', 'kabupaten', NULL, NULL),
            (6371, 63, 'banjarmasin', 'kota banjarmasin', 'kota', NULL, NULL),
            (6372, 63, 'banjar baru', 'kota banjar baru', 'kota', NULL, NULL),
            (6401, 64, 'paser', 'kabupaten paser', 'kabupaten', NULL, NULL),
            (6402, 64, 'kutai barat', 'kabupaten kutai barat', 'kabupaten', NULL, NULL),
            (6403, 64, 'kutai kartanegara', 'kabupaten kutai kartanegara', 'kabupaten', NULL, NULL),
            (6404, 64, 'kutai timur', 'kabupaten kutai timur', 'kabupaten', NULL, NULL),
            (6405, 64, 'berau', 'kabupaten berau', 'kabupaten', NULL, NULL),
            (6409, 64, 'penajam paser utara', 'kabupaten penajam paser utara', 'kabupaten', NULL, NULL),
            (6471, 64, 'balikpapan', 'kota balikpapan', 'kota', NULL, NULL),
            (6472, 64, 'samarinda', 'kota samarinda', 'kota', NULL, NULL),
            (6474, 64, 'bontang', 'kota bontang', 'kota', NULL, NULL),
            (6501, 65, 'malinau', 'kabupaten malinau', 'kabupaten', NULL, NULL),
            (6502, 65, 'bulungan', 'kabupaten bulungan', 'kabupaten', NULL, NULL),
            (6503, 65, 'tana tidung', 'kabupaten tana tidung', 'kabupaten', NULL, NULL),
            (6504, 65, 'nunukan', 'kabupaten nunukan', 'kabupaten', NULL, NULL),
            (6571, 65, 'tarakan', 'kota tarakan', 'kota', NULL, NULL),
            (7101, 71, 'bolaang mongondow', 'kabupaten bolaang mongondow', 'kabupaten', NULL, NULL),
            (7102, 71, 'minahasa', 'kabupaten minahasa', 'kabupaten', NULL, NULL),
            (7103, 71, 'kepulauan sangihe', 'kabupaten kepulauan sangihe', 'kabupaten', NULL, NULL),
            (7104, 71, 'kepulauan talaud', 'kabupaten kepulauan talaud', 'kabupaten', NULL, NULL),
            (7105, 71, 'minahasa selatan', 'kabupaten minahasa selatan', 'kabupaten', NULL, NULL),
            (7106, 71, 'minahasa utara', 'kabupaten minahasa utara', 'kabupaten', NULL, NULL),
            (7107, 71, 'bolaang mongondow utara', 'kabupaten bolaang mongondow utara', 'kabupaten', NULL, NULL),
            (7108, 71, 'siau tagulandang biaro', 'kabupaten siau tagulandang biaro', 'kabupaten', NULL, NULL),
            (7109, 71, 'minahasa tenggara', 'kabupaten minahasa tenggara', 'kabupaten', NULL, NULL),
            (7110, 71, 'bolaang mongondow selatan', 'kabupaten bolaang mongondow selatan', 'kabupaten', NULL, NULL),
            (7111, 71, 'bolaang mongondow timur', 'kabupaten bolaang mongondow timur', 'kabupaten', NULL, NULL),
            (7171, 71, 'manado', 'kota manado', 'kota', NULL, NULL),
            (7172, 71, 'bitung', 'kota bitung', 'kota', NULL, NULL),
            (7173, 71, 'tomohon', 'kota tomohon', 'kota', NULL, NULL),
            (7174, 71, 'kotamobagu', 'kota kotamobagu', 'kota', NULL, NULL),
            (7201, 72, 'banggai kepulauan', 'kabupaten banggai kepulauan', 'kabupaten', NULL, NULL),
            (7202, 72, 'banggai', 'kabupaten banggai', 'kabupaten', NULL, NULL),
            (7203, 72, 'morowali', 'kabupaten morowali', 'kabupaten', NULL, NULL),
            (7204, 72, 'poso', 'kabupaten poso', 'kabupaten', NULL, NULL),
            (7205, 72, 'donggala', 'kabupaten donggala', 'kabupaten', NULL, NULL),
            (7206, 72, 'toli-toli', 'kabupaten toli-toli', 'kabupaten', NULL, NULL),
            (7207, 72, 'buol', 'kabupaten buol', 'kabupaten', NULL, NULL),
            (7208, 72, 'parigi moutong', 'kabupaten parigi moutong', 'kabupaten', NULL, NULL),
            (7209, 72, 'tojo una-una', 'kabupaten tojo una-una', 'kabupaten', NULL, NULL),
            (7210, 72, 'sigi', 'kabupaten sigi', 'kabupaten', NULL, NULL),
            (7271, 72, 'palu', 'kota palu', 'kota', NULL, NULL),
            (7301, 73, 'kepulauan selayar', 'kabupaten kepulauan selayar', 'kabupaten', NULL, NULL),
            (7302, 73, 'bulukumba', 'kabupaten bulukumba', 'kabupaten', NULL, NULL),
            (7303, 73, 'bantaeng', 'kabupaten bantaeng', 'kabupaten', NULL, NULL),
            (7304, 73, 'jeneponto', 'kabupaten jeneponto', 'kabupaten', NULL, NULL),
            (7305, 73, 'takalar', 'kabupaten takalar', 'kabupaten', NULL, NULL),
            (7306, 73, 'gowa', 'kabupaten gowa', 'kabupaten', NULL, NULL),
            (7307, 73, 'sinjai', 'kabupaten sinjai', 'kabupaten', NULL, NULL),
            (7308, 73, 'maros', 'kabupaten maros', 'kabupaten', NULL, NULL),
            (7309, 73, 'pangkajene dan kepulauan', 'kabupaten pangkajene dan kepulauan', 'kabupaten', NULL, NULL),
            (7310, 73, 'barru', 'kabupaten barru', 'kabupaten', NULL, NULL),
            (7311, 73, 'bone', 'kabupaten bone', 'kabupaten', NULL, NULL),
            (7312, 73, 'soppeng', 'kabupaten soppeng', 'kabupaten', NULL, NULL),
            (7313, 73, 'wajo', 'kabupaten wajo', 'kabupaten', NULL, NULL),
            (7314, 73, 'sidenreng rappang', 'kabupaten sidenreng rappang', 'kabupaten', NULL, NULL),
            (7315, 73, 'pinrang', 'kabupaten pinrang', 'kabupaten', NULL, NULL),
            (7316, 73, 'enrekang', 'kabupaten enrekang', 'kabupaten', NULL, NULL),
            (7317, 73, 'luwu', 'kabupaten luwu', 'kabupaten', NULL, NULL),
            (7318, 73, 'tana toraja', 'kabupaten tana toraja', 'kabupaten', NULL, NULL),
            (7322, 73, 'luwu utara', 'kabupaten luwu utara', 'kabupaten', NULL, NULL),
            (7325, 73, 'luwu timur', 'kabupaten luwu timur', 'kabupaten', NULL, NULL),
            (7326, 73, 'toraja utara', 'kabupaten toraja utara', 'kabupaten', NULL, NULL),
            (7371, 73, 'makassar', 'kota makassar', 'kota', NULL, NULL),
            (7372, 73, 'parepare', 'kota parepare', 'kota', NULL, NULL),
            (7373, 73, 'palopo', 'kota palopo', 'kota', NULL, NULL),
            (7401, 74, 'buton', 'kabupaten buton', 'kabupaten', NULL, NULL),
            (7402, 74, 'muna', 'kabupaten muna', 'kabupaten', NULL, NULL),
            (7403, 74, 'konawe', 'kabupaten konawe', 'kabupaten', NULL, NULL),
            (7404, 74, 'kolaka', 'kabupaten kolaka', 'kabupaten', NULL, NULL),
            (7405, 74, 'konawe selatan', 'kabupaten konawe selatan', 'kabupaten', NULL, NULL),
            (7406, 74, 'bombana', 'kabupaten bombana', 'kabupaten', NULL, NULL),
            (7407, 74, 'wakatobi', 'kabupaten wakatobi', 'kabupaten', NULL, NULL),
            (7408, 74, 'kolaka utara', 'kabupaten kolaka utara', 'kabupaten', NULL, NULL),
            (7409, 74, 'buton utara', 'kabupaten buton utara', 'kabupaten', NULL, NULL),
            (7410, 74, 'konawe utara', 'kabupaten konawe utara', 'kabupaten', NULL, NULL),
            (7471, 74, 'kendari', 'kota kendari', 'kota', NULL, NULL),
            (7472, 74, 'baubau', 'kota baubau', 'kota', NULL, NULL),
            (7501, 75, 'boalemo', 'kabupaten boalemo', 'kabupaten', NULL, NULL),
            (7502, 75, 'gorontalo', 'kabupaten gorontalo', 'kabupaten', NULL, NULL),
            (7503, 75, 'pohuwato', 'kabupaten pohuwato', 'kabupaten', NULL, NULL),
            (7504, 75, 'bone bolango', 'kabupaten bone bolango', 'kabupaten', NULL, NULL),
            (7505, 75, 'gorontalo utara', 'kabupaten gorontalo utara', 'kabupaten', NULL, NULL),
            (7571, 75, 'gorontalo', 'kota gorontalo', 'kota', NULL, NULL),
            (7601, 76, 'majene', 'kabupaten majene', 'kabupaten', NULL, NULL),
            (7602, 76, 'polewali mandar', 'kabupaten polewali mandar', 'kabupaten', NULL, NULL),
            (7603, 76, 'mamasa', 'kabupaten mamasa', 'kabupaten', NULL, NULL),
            (7604, 76, 'mamuju', 'kabupaten mamuju', 'kabupaten', NULL, NULL),
            (7605, 76, 'mamuju utara', 'kabupaten mamuju utara', 'kabupaten', NULL, NULL),
            (8101, 81, 'maluku tenggara barat', 'kabupaten maluku tenggara barat', 'kabupaten', NULL, NULL),
            (8102, 81, 'maluku tenggara', 'kabupaten maluku tenggara', 'kabupaten', NULL, NULL),
            (8103, 81, 'maluku tengah', 'kabupaten maluku tengah', 'kabupaten', NULL, NULL),
            (8104, 81, 'buru', 'kabupaten buru', 'kabupaten', NULL, NULL),
            (8105, 81, 'kepulauan aru', 'kabupaten kepulauan aru', 'kabupaten', NULL, NULL),
            (8106, 81, 'seram bagian barat', 'kabupaten seram bagian barat', 'kabupaten', NULL, NULL),
            (8107, 81, 'seram bagian timur', 'kabupaten seram bagian timur', 'kabupaten', NULL, NULL),
            (8108, 81, 'maluku barat daya', 'kabupaten maluku barat daya', 'kabupaten', NULL, NULL),
            (8109, 81, 'buru selatan', 'kabupaten buru selatan', 'kabupaten', NULL, NULL),
            (8171, 81, 'ambon', 'kota ambon', 'kota', NULL, NULL),
            (8172, 81, 'tual', 'kota tual', 'kota', NULL, NULL),
            (8201, 82, 'halmahera barat', 'kabupaten halmahera barat', 'kabupaten', NULL, NULL),
            (8202, 82, 'halmahera tengah', 'kabupaten halmahera tengah', 'kabupaten', NULL, NULL),
            (8203, 82, 'kepulauan sula', 'kabupaten kepulauan sula', 'kabupaten', NULL, NULL),
            (8204, 82, 'halmahera selatan', 'kabupaten halmahera selatan', 'kabupaten', NULL, NULL),
            (8205, 82, 'halmahera utara', 'kabupaten halmahera utara', 'kabupaten', NULL, NULL),
            (8206, 82, 'halmahera timur', 'kabupaten halmahera timur', 'kabupaten', NULL, NULL),
            (8207, 82, 'pulau morotai', 'kabupaten pulau morotai', 'kabupaten', NULL, NULL),
            (8271, 82, 'ternate', 'kota ternate', 'kota', NULL, NULL),
            (8272, 82, 'tidore kepulauan', 'kota tidore kepulauan', 'kota', NULL, NULL),
            (9101, 91, 'fakfak', 'kabupaten fakfak', 'kabupaten', NULL, NULL),
            (9102, 91, 'kaimana', 'kabupaten kaimana', 'kabupaten', NULL, NULL),
            (9103, 91, 'teluk wondama', 'kabupaten teluk wondama', 'kabupaten', NULL, NULL),
            (9104, 91, 'teluk bintuni', 'kabupaten teluk bintuni', 'kabupaten', NULL, NULL),
            (9105, 91, 'manokwari', 'kabupaten manokwari', 'kabupaten', NULL, NULL),
            (9106, 91, 'sorong selatan', 'kabupaten sorong selatan', 'kabupaten', NULL, NULL),
            (9107, 91, 'sorong', 'kabupaten sorong', 'kabupaten', NULL, NULL),
            (9108, 91, 'raja ampat', 'kabupaten raja ampat', 'kabupaten', NULL, NULL),
            (9109, 91, 'tambrauw', 'kabupaten tambrauw', 'kabupaten', NULL, NULL),
            (9110, 91, 'maybrat', 'kabupaten maybrat', 'kabupaten', NULL, NULL),
            (9171, 91, 'sorong', 'kota sorong', 'kota', NULL, NULL),
            (9401, 94, 'merauke', 'kabupaten merauke', 'kabupaten', NULL, NULL),
            (9402, 94, 'jayawijaya', 'kabupaten jayawijaya', 'kabupaten', NULL, NULL),
            (9403, 94, 'jayapura', 'kabupaten jayapura', 'kabupaten', NULL, NULL),
            (9404, 94, 'nabire', 'kabupaten nabire', 'kabupaten', NULL, NULL),
            (9408, 94, 'kepulauan yapen', 'kabupaten kepulauan yapen', 'kabupaten', NULL, NULL),
            (9409, 94, 'biak numfor', 'kabupaten biak numfor', 'kabupaten', NULL, NULL),
            (9410, 94, 'paniai', 'kabupaten paniai', 'kabupaten', NULL, NULL),
            (9411, 94, 'puncak jaya', 'kabupaten puncak jaya', 'kabupaten', NULL, NULL),
            (9412, 94, 'mimika', 'kabupaten mimika', 'kabupaten', NULL, NULL),
            (9413, 94, 'boven digoel', 'kabupaten boven digoel', 'kabupaten', NULL, NULL),
            (9414, 94, 'mappi', 'kabupaten mappi', 'kabupaten', NULL, NULL),
            (9415, 94, 'asmat', 'kabupaten asmat', 'kabupaten', NULL, NULL),
            (9416, 94, 'yahukimo', 'kabupaten yahukimo', 'kabupaten', NULL, NULL),
            (9417, 94, 'pegunungan bintang', 'kabupaten pegunungan bintang', 'kabupaten', NULL, NULL),
            (9418, 94, 'tolikara', 'kabupaten tolikara', 'kabupaten', NULL, NULL),
            (9419, 94, 'sarmi', 'kabupaten sarmi', 'kabupaten', NULL, NULL),
            (9420, 94, 'keerom', 'kabupaten keerom', 'kabupaten', NULL, NULL),
            (9426, 94, 'waropen', 'kabupaten waropen', 'kabupaten', NULL, NULL),
            (9427, 94, 'supiori', 'kabupaten supiori', 'kabupaten', NULL, NULL),
            (9428, 94, 'mamberamo raya', 'kabupaten mamberamo raya', 'kabupaten', NULL, NULL),
            (9429, 94, 'nduga', 'kabupaten nduga', 'kabupaten', NULL, NULL),
            (9430, 94, 'lanny jaya', 'kabupaten lanny jaya', 'kabupaten', NULL, NULL),
            (9431, 94, 'mamberamo tengah', 'kabupaten mamberamo tengah', 'kabupaten', NULL, NULL),
            (9432, 94, 'yalimo', 'kabupaten yalimo', 'kabupaten', NULL, NULL),
            (9433, 94, 'puncak', 'kabupaten puncak', 'kabupaten', NULL, NULL),
            (9434, 94, 'dogiyai', 'kabupaten dogiyai', 'kabupaten', NULL, NULL),
            (9435, 94, 'intan jaya', 'kabupaten intan jaya', 'kabupaten', NULL, NULL),
            (9436, 94, 'deiyai', 'kabupaten deiyai', 'kabupaten', NULL, NULL),
            (9471, 94, 'jayapura ', 'kota jayapura ', 'kota', NULL, NULL)"
        );

    }
}
